/**
 * Wellness imagery constants — maps pillar IDs, stat types, and page contexts
 * to generated image paths in /images/wellness/.
 *
 * Generated by: scripts/generate-wellness-assets.js (Imagen 4)
 */

import type { PillarId } from './constants'

const BASE = '/images/wellness'

// Pillar illustrations (80-120px, 1:1, for card headers/corners)
export const PILLAR_IMAGES: Record<PillarId, string> = {
  identity: `${BASE}/pillar-identity.png`,
  emotional: `${BASE}/pillar-emotional.png`,
  physical: `${BASE}/pillar-physical.png`,
  connection: `${BASE}/pillar-connection.png`,
  mission: `${BASE}/pillar-mission.png`,
}

// Stat card illustrations (80-120px, 1:1, for stat card decoration)
export const STAT_IMAGES = {
  goals: `${BASE}/stat-goals.png`,
  streak: `${BASE}/stat-streak.png`,
  connections: `${BASE}/stat-connections.png`,
  progress: `${BASE}/stat-progress.png`,
  active: `${BASE}/stat-active.png`,
  completed: `${BASE}/stat-completed.png`,
} as const

// Empty state illustrations (200-300px, 4:3, for empty page states)
export const EMPTY_STATE_IMAGES = {
  goals: `${BASE}/empty-goals.png`,
  kpis: `${BASE}/empty-kpis.png`,
  protocols: `${BASE}/empty-protocols.png`,
  sessions: `${BASE}/empty-sessions.png`,
  events: `${BASE}/empty-events.png`,
  accountability: `${BASE}/empty-accountability.png`,
} as const

// Background accent images (300-400px, 16:9, used at 5-10% opacity)
export const BG_IMAGES = {
  physical: `${BASE}/bg-physical.png`,
  emotional: `${BASE}/bg-emotional.png`,
  mission: `${BASE}/bg-mission.png`,
  vitality: `${BASE}/bg-vitality.png`,
  growth: `${BASE}/bg-growth.png`,
} as const
